// AUTO-GENERATED by scripts/sync-vinyl.mjs — do not edit by hand.
// Source: Obsidian vault Music folder. Run `npm run sync-vinyl` to refresh.
import type { VinylRecord } from "./vinyl";

export const records: VinylRecord[] = [
  {
    id: "double-infinity",
    artist: "Big Thief",
    title: "Double Infinity",
    releaseDate: "2025-06-04",
    coverSrc: "/vinyl/double-infinity.jpg",
    coverAlt: "Double Infinity by Big Thief album cover",
  },
  {
    id: "double-natural",
    artist: "Boomgates",
    title: "Double Natural",
    releaseDate: "2012-08-31",
    coverSrc: "/vinyl/double-natural.jpg",
    coverAlt: "Double Natural by Boomgates album cover",
  },
  {
    id: "fenceline",
    artist: "Mildred",
    title: "Fenceline",
    releaseDate: "2026-04-24",
    coverSrc: "/vinyl/fenceline.jpg",
    coverAlt: "Fenceline by Mildred album cover",
  },
  {
    id: "roses",
    artist: "Widowspeak",
    title: "Roses",
    releaseDate: "2026-06-05",
    coverSrc: "/vinyl/roses.jpg",
    coverAlt: "Roses by Widowspeak album cover",
  },
  {
    id: "the-car",
    artist: "Arctic Monkeys",
    title: "The Car",
    releaseDate: "2022-10-21",
    coverSrc: "/vinyl/the-car.jpg",
    coverAlt: "The Car by Arctic Monkeys album cover",
  },
  {
    id: "the-man-from-waco",
    artist: "Charley Crockett",
    title: "The Man from Waco",
    releaseDate: "2022-09-09",
    coverSrc: "/vinyl/the-man-from-waco.jpg",
    coverAlt: "The Man from Waco by Charley Crockett album cover",
  },
  {
    id: "twilight-override",
    artist: "Jeff Tweedy",
    title: "Twilight Override",
    releaseDate: "2025-09-26",
    coverSrc: "/vinyl/twilight-override.jpg",
    coverAlt: "Twilight Override by Jeff Tweedy album cover",
  },
  {
    id: "volumes-one-selections-from-music-concerts-2019-2023-bon-iver-6-piece-band",
    artist: "Bon Iver",
    title: "Volumes: One - Selections From Music Concerts 2019-2023 Bon Iver 6 Piece Band",
    releaseDate: "2026-04-03",
    coverSrc: "/vinyl/volumes-one-selections-from-music-concerts-2019-2023-bon-iver-6-piece-band.jpg",
    coverAlt: "Volumes: One - Selections From Music Concerts 2019-2023 Bon Iver 6 Piece Band by Bon Iver album cover",
  },
];
