// AUTO-GENERATED by scripts/sync-vinyl.mjs — do not edit by hand.
// Source: Obsidian vault Music folder. Run `npm run sync-vinyl` to refresh.
import type { VinylRecord } from "./vinyl";

export const records: VinylRecord[] = [
  {
    id: "double-infinity",
    artist: "Big Thief",
    title: "Double Infinity",
    releaseDate: "2025",
    coverSrc: "/vinyl/double-infinity.jpg",
    coverAlt: "Double Infinity by Big Thief album cover",
  },
  {
    id: "fenceline",
    artist: "Mildred",
    title: "Fenceline",
    releaseDate: "2026",
    coverSrc: "/vinyl/fenceline.jpg",
    coverAlt: "Fenceline by Mildred album cover",
  },
  {
    id: "roses",
    artist: "Widowspeak",
    title: "Roses",
    releaseDate: "2026",
    coverSrc: "/vinyl/roses.jpg",
    coverAlt: "Roses by Widowspeak album cover",
  },
  {
    id: "the-car",
    artist: "Arctic Monkeys",
    title: "The Car",
    releaseDate: "2022",
    coverSrc: "/vinyl/the-car.jpg",
    coverAlt: "The Car by Arctic Monkeys album cover",
  },
  {
    id: "the-man-from-waco",
    artist: "Charley Crockett",
    title: "The Man from Waco",
    releaseDate: "2022",
    coverSrc: "/vinyl/the-man-from-waco.jpg",
    coverAlt: "The Man from Waco by Charley Crockett album cover",
  },
  {
    id: "twilight-override",
    artist: "Jeff Tweedy",
    title: "Twilight Override",
    releaseDate: "2025",
    coverSrc: "/vinyl/twilight-override.jpg",
    coverAlt: "Twilight Override by Jeff Tweedy album cover",
  },
];
